/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nuolmakermanager;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author xang-
 */
public class frmMainNuolMaker extends javax.swing.JFrame {

    /**
     * Creates new form frmMainNuolMaker
     */
    
    Dimension dimension=Toolkit.getDefaultToolkit().getScreenSize(); //get dimension screensize
          
    
    public frmMainNuolMaker() {
        initComponents();
        int width=dimension.width+5;
        int heigth=dimension.height+5;
        setBounds(0, 0, width, heigth); //set full screen 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuBar.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N

        fileMenu.setMnemonic('f');
        fileMenu.setText("Robot");
        fileMenu.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N

        jMenu1.setText("ຕັ້ງຄ່າ");
        jMenu1.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        jMenuItem1.setText("ອັດຕາແລກປ່ຽນ");
        jMenu1.add(jMenuItem1);

        fileMenu.add(jMenu1);

        saveMenuItem.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("ອອກ");
        saveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("ຈັດການຂໍ້ມູນພື້ນຖານ");
        editMenu.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N

        cutMenuItem.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("ຈັດການຂໍ້ມູນສະມາຊິກ");
        editMenu.add(cutMenuItem);

        copyMenuItem.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        jMenu2.setText("ຂື້ນແຜ່ນ");
        jMenu2.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        jMenu2.add(jMenuItem2);

        menuBar.add(jMenu2);

        helpMenu.setMnemonic('h');
        helpMenu.setText("ລາຍງານ");
        helpMenu.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N

        contentMenuItem.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("ລາຍງານເເຜ່ນປະຈຸບັນ");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("ລາຍງານເເຜ່ນປະຈຳເດືອນ");
        helpMenu.add(aboutMenuItem);

        jMenuItem3.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        jMenuItem3.setText("ລາຍງານເເຜ່ນປະຈຳປິ");
        helpMenu.add(jMenuItem3);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItemActionPerformed
     
      int confirm=  JOptionPane.showConfirmDialog(null, "do you want to exit program", "NuolMakerManager", JOptionPane.OK_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE);
      
        if(confirm==JOptionPane.OK_OPTION){
            System.exit(0);
        }else{
            return;
        }
                
                
    }//GEN-LAST:event_saveMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMainNuolMaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMainNuolMaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMainNuolMaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMainNuolMaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMainNuolMaker().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables

}
