/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nuolmakermanager;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author xang-
 */
public class frmMainNuolMaker extends javax.swing.JFrame {

    /**
     * Creates new form frmMainNuolMaker
     */
    
    Dimension dimension=Toolkit.getDefaultToolkit().getScreenSize(); //get dimension screensize
          
    
    public frmMainNuolMaker() {
        initComponents();
        int width=dimension.width+5;
        int heigth=dimension.height+5;
        setBounds(0, 0, width, heigth); //set full screen 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("status:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 340, 20));

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 253, Short.MAX_VALUE)
        );

        getContentPane().add(desktopPane, java.awt.BorderLayout.CENTER);

        menuBar.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N

        fileMenu.setMnemonic('f');
        fileMenu.setText("Robot");
        fileMenu.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N

        jMenu1.setText("ຕັ້ງຄ່າ");
        jMenu1.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        jMenuItem1.setText("ອັດຕາແລກປ່ຽນ");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        fileMenu.add(jMenu1);

        saveMenuItem.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("ອອກ");
        saveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("ຈັດການຂໍ້ມູນພື້ນຖານ");
        editMenu.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N

        cutMenuItem.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("ຂໍ້ມູນສະມາຊິກ");
        cutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(cutMenuItem);

        copyMenuItem.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("ຂໍ້ມູນເຂົ້າສູ່ລະບົບ");
        copyMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(copyMenuItem);

        jMenuItem5.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        jMenuItem5.setText("ຂໍ້ມູນລາຍຈ່າຍພິເສດ");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        editMenu.add(jMenuItem5);

        jMenuItem6.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        jMenuItem6.setText("ຂໍ້ມູນງົມປະມານ");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        editMenu.add(jMenuItem6);

        jMenuItem7.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        jMenuItem7.setText("ຂໍ້ມູນຊື້ອຸປະກອນ");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        editMenu.add(jMenuItem7);

        jMenuItem9.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        jMenuItem9.setText("ຂໍ້ມູນປະເພດອຸປະກອນ");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        editMenu.add(jMenuItem9);

        menuBar.add(editMenu);

        jMenu2.setText("ຂື້ນແຜ່ນ");
        jMenu2.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N

        jMenuItem2.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        jMenuItem2.setText("ເພີ່ມແຜນງານ");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem4.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        jMenuItem4.setText("ຂຽນແຜນງານ");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem8.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        jMenuItem8.setText("Commit ແຜນງານ");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        menuBar.add(jMenu2);

        helpMenu.setMnemonic('h');
        helpMenu.setText("ລາຍງານ");
        helpMenu.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N

        contentMenuItem.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("ລາຍງານເເຜ່ນປະຈຸບັນ");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("ລາຍງານເເຜ່ນປະຈຳເດືອນ");
        helpMenu.add(aboutMenuItem);

        jMenuItem3.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        jMenuItem3.setText("ລາຍງານເເຜ່ນປະຈຳປິ");
        helpMenu.add(jMenuItem3);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItemActionPerformed
     
      int confirm=  JOptionPane.showConfirmDialog(null, "do you want to exit program", "NuolMakerManager", JOptionPane.OK_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE);
      
        if(confirm==JOptionPane.OK_OPTION){
            System.exit(0);
        }else{
            return;
        }
                
                
    }//GEN-LAST:event_saveMenuItemActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
     
        frmPlanManager planManager=new frmPlanManager();
        planManager.setTitle("Plan Manager");
        desktopPane.add(planManager);
        planManager.show();
        
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void cutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutMenuItemActionPerformed
      //  frmMemberManager mem=new frmMemberManager();
        nuolmakermanager.frmMemberManager mem1=new nuolmakermanager.frmMemberManager();
        desktopPane.add(mem1);
          mem1.show();
                 
                  
    }//GEN-LAST:event_cutMenuItemActionPerformed

    private void copyMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyMenuItemActionPerformed
        // TODO add your handling code here:
        nuolmakermanager.frmSystemLoginMaanger st=new nuolmakermanager.frmSystemLoginMaanger();
        desktopPane.add(st);
        st.show();
    }//GEN-LAST:event_copyMenuItemActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        frmfinance fin=new frmfinance();
        desktopPane.add(fin);
        fin.show();
        
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
       frmSpacilePayManager spcp=new frmSpacilePayManager();
       desktopPane.add(spcp);
       spcp.show();
       
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        frmbuyManager by=new frmbuyManager();
        desktopPane.add(by);
        by.show();
        
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        frmtypeAccessories typacc=new frmtypeAccessories();
        desktopPane.add(typacc);
        typacc.show();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        frmPlanManager pm=new frmPlanManager();
        desktopPane.add(pm);
        pm.show();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        frmCommit commit=new frmCommit();
        desktopPane.add(commit);
        commit.show();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMainNuolMaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMainNuolMaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMainNuolMaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMainNuolMaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMainNuolMaker().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables

}
