/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nuolmakermanager;

/**
 *
 * @author xang-
 */
public class frmSpacilePayManager extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmPlanSpacilePayManager
     */
    public frmSpacilePayManager() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtcash = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        btupdate = new javax.swing.JButton();
        btchoose = new javax.swing.JButton();
        btdelect = new javax.swing.JButton();
        btadd = new javax.swing.JButton();
        txtproductname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txttotal = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);

        jPanel1.setPreferredSize(new java.awt.Dimension(552, 200));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        jLabel2.setText("ເປັນເງິນ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        txtcash.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        jPanel1.add(txtcash, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 220, 30));

        jTextField2.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        jTextField2.setText("ແຜນງານ");
        jTextField2.setEnabled(false);
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 220, 30));

        btupdate.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        btupdate.setText("ອັບເດດ");
        jPanel1.add(btupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));

        btchoose.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        btchoose.setText("ເລືອກ");
        jPanel1.add(btchoose, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 70, 30));

        btdelect.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        btdelect.setText("ລົບ");
        jPanel1.add(btdelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 70, -1));

        btadd.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        btadd.setText("ເພິມ");
        jPanel1.add(btadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 70, -1));

        txtproductname.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        jPanel1.add(txtproductname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 220, 30));

        jLabel3.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        jLabel3.setText("ຊື່ລາຍຈ່າຍພິເສດ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ລວມເປັນເງິນ(ກິບ)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Saysettha OT", 0, 12))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txttotal.setBackground(new java.awt.Color(0, 0, 0));
        txttotal.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        txttotal.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 180, 100));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 210, 180));

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jTable1.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btadd;
    private javax.swing.JButton btchoose;
    private javax.swing.JButton btdelect;
    private javax.swing.JButton btupdate;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField txtcash;
    private javax.swing.JTextField txtproductname;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
