/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nuolmakermanager;

/**
 *
 * @author xang-
 */
public class frmWritePlan extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmorder
     */
    public frmWritePlan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        btchoose = new javax.swing.JButton();
        txtprice = new javax.swing.JTextField();
        txtequipname = new javax.swing.JTextField();
        txtamount = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        combotype = new javax.swing.JComboBox<String>();
        btadd = new javax.swing.JButton();
        btdelete = new javax.swing.JButton();
        btupdate = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtspecialpay = new javax.swing.JTextField();
        btbrown = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setAutoscrolls(true);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setPreferredSize(new java.awt.Dimension(590, 400));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Saysettha OT", 0, 11)); // NOI18N
        jTextField1.setText("ແຜ່ນການ");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 200, 30));

        btchoose.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        btchoose.setText("ເລືອກ");
        jPanel3.add(btchoose, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 60, 30));

        txtprice.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        jPanel3.add(txtprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 270, 30));

        txtequipname.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        jPanel3.add(txtequipname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 270, 30));

        txtamount.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        jPanel3.add(txtamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 270, 30));

        jLabel1.setFont(new java.awt.Font("Saysettha OT", 0, 14)); // NOI18N
        jLabel1.setText("ລາຄາ");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 50, 30));

        jLabel2.setFont(new java.awt.Font("Saysettha OT", 0, 14)); // NOI18N
        jLabel2.setText("ຊື່ອຸປະກອນ");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 70, 30));

        jLabel3.setFont(new java.awt.Font("Saysettha OT", 0, 14)); // NOI18N
        jLabel3.setText("ຊະນິດ");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 50, 30));

        jLabel4.setFont(new java.awt.Font("Saysettha OT", 0, 14)); // NOI18N
        jLabel4.setText("ຈຳນວນ");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 50, 30));

        combotype.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        combotype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(combotype, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 270, 30));

        btadd.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        btadd.setText("ເພີມ");
        jPanel3.add(btadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 100, 40));

        btdelete.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        btdelete.setText("ລົບ");
        jPanel3.add(btdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 100, 40));

        btupdate.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        btupdate.setText("ອັບເດດ");
        jPanel3.add(btupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 100, 40));

        jLabel5.setFont(new java.awt.Font("Saysettha OT", 0, 14)); // NOI18N
        jLabel5.setText("ລາຍຈ່າຍພິເສດ");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 90, 30));

        txtspecialpay.setEditable(false);
        txtspecialpay.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        jPanel3.add(txtspecialpay, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 270, 30));

        btbrown.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        btbrown.setText("...");
        btbrown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbrownActionPerformed(evt);
            }
        });
        jPanel3.add(btbrown, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 30, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 510, 350));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "ລວມຍອດເງິນ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Saysettha OT", 0, 12))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(0, 0, 0));
        jTextField6.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 210, 110));

        jTextField7.setEditable(false);
        jTextField7.setBackground(new java.awt.Color(0, 0, 0));
        jTextField7.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 210, 110));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 230, 360));

        jPanel2.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        setBounds(0, 0, 788, 684);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btbrownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbrownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btbrownActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btadd;
    private javax.swing.JButton btbrown;
    private javax.swing.JButton btchoose;
    private javax.swing.JButton btdelete;
    private javax.swing.JButton btupdate;
    private javax.swing.JComboBox<String> combotype;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField txtamount;
    private javax.swing.JTextField txtequipname;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtspecialpay;
    // End of variables declaration//GEN-END:variables
}
